version: "3"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Anchorage
    volumes:
      - config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: always
volumes:
  config:
